name: deployment Docker

on:
  workflow_dispatch:
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse a AWS y actualizar contenedor
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}
          
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/reserva-back:latest

            sudo docker stop reserva-back || true
            sudo docker rm reserva-back || true
            sudo docker run -d \
              -p 8080:8080 \
              --name reserva-back \
              --network red-interna \
              -e DB_HOST="{{db_host}}" \
              -e DB_PORT=3306 \
              -e DB_NAME=reservas \
              -e DB_USER=${{ secrets.RDS_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/reserva-back:latest
            sudo docker system prune -f
