name: CI/CD Docker Hub

on:
  push:
    branches: [ "main" ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y Subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reserva-back:latest
          
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse a AWS y actualizar contenedor
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}
          
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/reserva-back:latest

            sudo docker stop reserva-back || true
            sudo docker rm reserva-back || true
            sudo docker run -d \
              -p 8080:8080 \
              --name reserva-back \
              --network red-interna \
              -e DB_HOST=${{ github.event.client_payload.db_host_rds }} \
              -e DB_PORT=3306 \
              -e DB_NAME=reservas \
              -e DB_USER=${{ secrets.RDS_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/reserva-back:latest
            sudo docker system prune -f
